### ISSUE TITLE
options page +Add back localstorage of event name

### ISSUE THREAD

**Issue by titaniumbones** [edgi-govdata-archiving/eot-nomination-tool#13]
There are a bunch of events coming up, some on the same day as each other; is probably a good idea to manually enter the event name (and psosibly also to manually select the government agency).  

This oculd be done w/ prompts as we did before, but would be better to have all the localStorage data in an "options" dialogue, if osmeone knows how to do that.

**Comment by mi-lee** [comment]
Could you specify what you mean by an options dialog? Do you mean something like http://photos1.blogger.com/blogger/674/1162/320/screenshot.gif for government agencies? Any other fields you want to include?

(Also apologies for the late reply - I'm currently on vacation!  🏖)

**Comment by mi-lee** [comment]
@titaniumbones was this what you had in mind? https://github.com/guerrilla-archiving/presidential-harvest-nomination-tool/pull/16

**Comment by titaniumbones** [comment]
wasn't quite what I had in mind but is better than my idea. 😕
