### ISSUE TITLE
Add options field specifying government agency

### ISSUE THREAD

**Issue by titaniumbones** [edgi-govdata-archiving/eot-nomination-tool#15]
New archivathon events are being planned all the time, and they will cover a bunch of different government agencies. The extension will be a lot more useful if users can set the government agency field, hopefully using the list from the UNT bookmarklet submission page: http://digital2.library.unt.edu/nomination/eth2016/url/https%3A//www.standforpeaceandjustice.org/#Agency 

This depends on #13, figuring out how options work.  Having it would b a big win though!

**Comment by mi-lee** [comment]
I took the list of gov agencies from the unt website and put it here: https://github.com/guerrilla-archiving/presidential-harvest-nomination-tool/pull/16

**Comment by titaniumbones** [comment]
it's great.  💃 :gunter: (alas poor gunter.  I miss him here.)
