### ISSUE TITLE
images

### ISSUE THREAD

**Issue by titaniumbones** [edgi-govdata-archiving/eot-nomination-tool#17]
Do you still want to add some images? I think they'd be great if you want to. Otherwise I can push out new version to store.

**Comment by sonalranjit** [comment]
Images for the extension? I think its okay, i was going to recommend the same gorilla as the github repo, if thats okay

**Comment by mi-lee** [comment]
I'm fine either way!

**Comment by titaniumbones** [comment]
ahh! right! shoot, I just figured that out.  Published yesterday w/out it, I will see what the risk-averse folks @ EDGI say.


Sonal Ranjit <notifications@github.com> writes:

> Images for the extension? I think its okay, i was going to recommend the same gorilla as the github repo, if thats okay
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.


--
