### ISSUE TITLE
Customize (in branch?) a version of tool with additional columns

### ISSUE THREAD

**Issue by dcwalk** [edgi-govdata-archiving/eot-nomination-tool#18]
Spoke with @sonalranjit about this tonight, we've had a request to customize the tool to help @ambergman @trinberg with their data collection. (also pinging @mi-lee!)

Is there any way ASAP to assist with adding in more fields? 

@ambergman @trinberg --
Can you specify: 1) field names 2) what range of values you are expecting/requiring?

**Comment by ambergman** [comment]
Thanks so much for helping us out with this @sonalranjit, @mi-lee, and @dcwalk! I've attached a schematic of what @trinberg and I think the extension could look like, with fields we are hoping to add and detailed information about why we feel the proposed fields would allow to interact with [this spreadsheet](https://docs.google.com/spreadsheets/d/11nCTBATDGABjRhgsFEtukAClsxCodkMgWW1GSLwLBfI/edit#gid=1041328002), allowing us to systematically keep track new URLs being added.

The 4 proposed fields will take single or double digit integers, so having the appropriate validations on the textbox or a 0-99 dropdown would work well. The names for each of the fields are included in the attached slides.

[Chrome Extension Mockup - 4 Additional Fields - 110117.pptx](https://github.com/edgi-govdata-archiving/presidential-harvest-nomination-tool/files/698119/Chrome.Extension.Mockup.-.4.Additional.Fields.-.110117.pptx)

**Comment by sonalranjit** [comment]
no worries @ambergman if you want your own spreadsheet, i would ask that you guys host a public google form such as [this](https://docs.google.com/forms/d/e/1FAIpQLSf6Yc_p3VjHELQOactjYGJIGpU4uwBg5omZAZsbTQZXbT87tQ/viewform) with your required input fields and share the editing with me @ sonal.ranjit3 AT gmail.com and michelle DOT mh DOT lee92 AT gmail DOT com so we can supply the inputs to your own sheet with the extension

**Comment by ambergman** [comment]
Thanks @sonalranjit. Just shared you on the Google form with you and @mi-lee. Not sure exactly how you think it's best to manage the "Required" setting; I've got them set for now as I think they might make sense, but feel free to edit them.

**Comment by sonalranjit** [comment]
just an update, the tool is ready for the option 4 as specified in the mockup. im just trying to do option 3. will update here once its done.

**Comment by mi-lee** [comment]
@ambergman question, does Agency Office Code & Sub-Primer Num have to be required to submit?

**Comment by mi-lee** [comment]
Me and @sonalranjit's work for the mockup here: https://github.com/edgi-govdata-archiving/presidential-harvest-nomination-tool/pull/19. Please let us know if this is what you had in mind

**Comment by trinberg** [comment]
Hi All -Thanks so much for your work on this! @ambergman had a busy night, so I looked over this branch. The modified extension looks great - we understand you probably couldn't fit everything on one line (if it stays that way, maybe we can just change num -> number)
A few points/questions:
1)  I'm not sure if I'm doing something wrong, but in the form/spreadsheet that's being populated, the id_agency/id_subagency/id_org/primer id fields are not being filled in for me. You can see the last three attempts I made [here](https://docs.google.com/spreadsheets/d/1eJO18Wl8alIvam1FHoKmOyg6vK8nxGGKIgdwEhm26g8/edit#gid=766232732). This seems like the main issue at the moment - any suggestions?
2) @mi-lee regarding your question - yes, the fields should be required, but users will be instructed to set to '0' if code is unknown. I think defaulting to '0' also makes sense.
3) It's great that option 3 is working. Once you populate the first agency office code, the top field auto-completes. One thing that may be worth fixing if you have time is that once you input into the agency office code, the agency dropdown list becomes locked out. It's not a big deal to click out of the extension and reset, so definitely don't bother if you don't have the time.
4) Eventually we should also map all of the dropdown entries to a number in the first agency office code box.

Thanks again - we really appreciate your work. Cheers, Toly

**Comment by sonalranjit** [comment]
@trinberg please try it with a non docs.google.com url, i was able to recreate it for the urls with docs.google.com , but it seems to be working for any other URL see sheet for test inputs.

**Comment by trinberg** [comment]
@sonalranjit thanks - good catch. it works for non google urls.

**Comment by sonalranjit** [comment]
I'm closing this if everything is okay. please respond to this if anything else is required.

**Comment by trinberg** [comment]
Hi @sonalranjit - we're having some conversations here at the Penn archiving event and we're wondering if it would be possible to add a checkbox to the chrome extension (EDGI Harvard branch), directly to the right of the "sub-primer num". Label above could be called: "Not crawlable:" I've also just added an extra field in the google form.

The event is happening tomorrow, but it would be good to test it soon.

**Comment by sonalranjit** [comment]
okay request is on #20 now, will update on that ticket @trinberg
