### ISSUE TITLE
success indication not reliable

### ISSUE THREAD

**Issue by titaniumbones** [edgi-govdata-archiving/eot-nomination-tool#22]
at least in the harvard-edgi branch, the "success" indicator doesn't always appear.

**Comment by atesgoral** [comment]
So, when this happens, there isn't an error shown either, right? Could it be that the Google Forms request isn't completed in time?

**Comment by titaniumbones** [comment]
That's my experience -- there's no message printed in the popup.  It also seems to me, though, that the result __is__ captured in the spreadsheet, so I would think that the request doesn't time out?

**Comment by sonalranjit** [comment]
Is this still occurring? I wasn't able to reproduce this, success message has been popping up fine for me. If this is not reoccurring then going to close this.

**Comment by sonalranjit** [comment]
Closing this since no one has submitted an occurrence of this issue.
