### ISSUE TITLE
sub-primer num field clears after submission

### ISSUE THREAD

**Issue by trinberg** [edgi-govdata-archiving/eot-nomination-tool#24]
the way people are using the tool now, the seeders stay in the same subsection for a long time so if all the fields stay populated that would be great.

**Comment by titaniumbones** [comment]
Want me to update that now?

**Comment by trinberg** [comment]
will people need to update their extension?

**Comment by titaniumbones** [comment]
Yes, and the changes haven't been made public yet -- will probably take 30 mins or so.  Also @atesgoral is trying to fix #25 I think.  @atesgoral consider dropping me yr email address in a DM somewhere so I can share spreadsheet URL with you!

**Comment by trinberg** [comment]
ok - well, you can reupload. people have their work flow down, but I can make an announcement once it's done. just ping me on slack when that's ready.

**Comment by titaniumbones** [comment]
fixed (lost track of commit #)
