### ISSUE TITLE
chrome extension takes a long time to open window

### ISSUE THREAD

**Issue by trinberg** [edgi-govdata-archiving/eot-nomination-tool#25]
I wanted to write this down: some people have been commenting that the extension has been taking longer to pop open. We're at ~2000 urls linked and maybe ~30 people using it now

**Comment by atesgoral** [comment]
Can we get some numbers? What sort of delay are people observing? Is it a slight sense of sluggishness or is it a crazy delay that's in the seconds?

**Comment by titaniumbones** [comment]
i see a noticeable delay esp. the first time I click on it in a session. Suggests to me there's some bottleneck. Are we loading any remote resources? Is there some cost to querying localStorage?

**Comment by atesgoral** [comment]
Bootstrap is being loaded from a CDN. And the browser doesn't seem to cache the responses. Using a local copy of Bootstrap might help a little. ~~Creating a PR soon.~~ Created #31.

**Comment by atesgoral** [comment]
#32 might also help a little. The option markup had redundant `value` attributes, bloating the amount of markup the browser needs to load & render. Actually, externalizing this data as JSON and lazily loading it might also help towards making the popup itself load faster.
