### ISSUE TITLE
Lack of URL-encoding of parameters, though things seem to work fine without it

### ISSUE THREAD

**Issue by atesgoral** [edgi-govdata-archiving/eot-nomination-tool#30]
Looking at the code, I found it scary that the query string parameters passed to the Google Forms API aren't being URL-encoded. A potential issue is when a submitted URL itself happens to contain a `&` and screws up the query string parsing of Google Forms.

However, after taking a quick glance at the accumulated data, I spotted URLs with query strings in them that were submitted fine.

I don't know how this ends up working fine, but we'd still be better off fortifying the way the query string is generated.

**Comment by titaniumbones** [comment]
I've been thinking this would be good, is probably a one-line fix right? If you know how to do it right away, the code should be in popup.js...

**Comment by atesgoral** [comment]
Yes, it's quick. I'm also tempted to do some cleanup along the way to make things easier to maintain. I'll take a look at it soon!

**Comment by atesgoral** [comment]
Just confirmed that this is an issue. If the submitted URL happens to have a `&` in it, the parameters following it will get dropped and get submitted to Google Forms instead. Some existing URLs unfortunately might already be broken this way. The potentially broken entries to look for are the ones with a `?` in the URL. Rest of the parameters will have been dropped and the site might respond with an error or take US to a different page altogether. These URLs might have to be culled after manual inspection.

**Comment by atesgoral** [comment]
Fix is in #33, but I haven't tested against the actual Google Form not to pollute it with test data.

**Comment by titaniumbones** [comment]
This seems important. Do you want to test it (I can delete your test responses afterwards), or should I just merge right away?

**Comment by dcwalk** [comment]
I reviewed but do not think I am qualified to approve PR #33, if makes sense but I don't work jQuery often enough

**Comment by atesgoral** [comment]
@titaniumbones I just tested it. Looks good!

**Comment by atesgoral** [comment]
Fixed by #33.
