### ISSUE TITLE
Extension didn't record responses on 1/24 

### ISSUE THREAD

**Issue by mayaad** [edgi-govdata-archiving/eot-nomination-tool#37]
Two of the CPF interns were seeding from their primers around 11pm on 1/24, and neither of their responses made it into the spreadsheet. I've skyped with each of them to confirm that they are using the extension properly, and they also both tried again and I could see their response pop up in the spreadsheet. 

Interesting to note that they definitely submitted something, since their extension autofilled with the correct information. 

Also, Toly mentioned that he had added extra rows to the google spreadsheet this morning. Not sure if that's related.

**Comment by sonalranjit** [comment]
The current sheet is getting massive, when testing some entries do take a long time to be recorded.  A better store for URLs as suggested on #35 would be ideal.

**Comment by titaniumbones** [comment]
I'm feeling this should be tagged wontfix and closed, anyone think different?

**Comment by mayaad** [comment]
@titaniumbones that's fine with me.

**Comment by dcwalk** [comment]
I agree
