### ISSUE TITLE
Add another set of fields to form/extension

### ISSUE THREAD

**Issue by titaniumbones** [edgi-govdata-archiving/eot-nomination-tool#38]
EDGI/Data Rescue folks have asked for yet another set of extra fields for the extension. In particular:
- REMOVE "Uncrawlable content?" checkbox -- we are deprecating this category
- REPLACE "Uncrawlable" category with 3 additional checkboxes: FTP?; Visualization?; Complex/hard?
- ADD Comment text field

Obviously those fields will also have to be added to [the form](https://docs.google.com/forms/d/1udxf9C7XeO7rm-SoucjDIv0c8XzGb7VVutsCI8r4s-Y)

Since we are already at the limit of the height allotment for dropdown extension windows, this will also require some CSS/html structure work in the popup window code.

**Comment by dcwalk** [comment]
@ambergman any thoughts?

**Comment by trinberg** [comment]
@titaniumbones @dcwalk @sonalranjit - Sorry for the rushed timeline on this, but we're hosting the Boston DataRescue starting at **4:30pm Today (Wednesday)**. Do you think you all would be able to put in the following changes/suggestions:

- REPLACE "Visualization" text with "Visualization/Interactive"
- REPLACE "Complex/Hard" text with "Many Files"
- ADD checkbox field with a header "Database"

@ambergman and I think the comment field is useful, but the added cost is that it makes the extension too big and produces the scrollbar. For now, I'd suggest: 
- REMOVE  "comment" header and comment input box

Regarding formatting: If possible, keep the chrome extension as small in height as possible - the scrollbar can be difficult on certain machines/browsers.

I already updated the form to reflect those changes. Let us know if you think you'll be able to get this done and if we can help in any way. Thanks so much!

**Comment by sonalranjit** [comment]
Closing this, the extension has been update as of #39
