### ISSUE TITLE
Add "reset" to allow people to fix typos

### ISSUE THREAD

**Issue by titaniumbones** [edgi-govdata-archiving/eot-nomination-tool#4]
Add a "reset options' command (maybe in a dropdown menu under the icon) to allow people to change identity or fix typos.

**Comment by mi-lee** [comment]
Change identity - could you specify that? localstorage is overwritten everytime the newest entry is different from the previous one.

**Comment by titaniumbones** [comment]
oh, duh, never mind, closing.
