### ISSUE TITLE
Rename repo?

### ISSUE THREAD

**Issue by dcwalk** [edgi-govdata-archiving/eot-nomination-tool#41]
Hey, just wondering if we could maybe rename this repo to something like `nomination-extension` or `eot-nomination-tool`?

"Harvest" is a bit confusing with the terminology from DataRefuge ("Harvestors" download data), and we've used "End of Term"/eot elsewhere, which I think is more intuitive than Presidential?

**Comment by dcwalk** [comment]
@sonalranjit @atesgoral @titaniumbones @ambergman or @trinberg, thoughts?

**Comment by titaniumbones** [comment]
do it! but you may need to update various docs.  and do it real quick
before @ebarry sends out her links...

**Comment by dcwalk** [comment]
In Chrome Store as "NominationTool" so I think we keep close to that?

**Comment by titaniumbones** [comment]
renaming to eot-nomination-tool
dcwalk <notifications@github.com> writes:

> Hey, just wondering if we could maybe rename this repo to something like `nomination-extension` or `eot-nomination-tool`?
>
> "Harvest" is a bit confusing with the terminology from DataRefuge ("Harvestors" download data), and we've used "End of Term"/eot elsewhere, which I think is more intuitive than Presidential?


--
