### ISSUE TITLE
Database Checkbox Not Working

### ISSUE THREAD

**Issue by trinberg** [edgi-govdata-archiving/eot-nomination-tool#44]
Hi All - Thanks again for your quick work before the event.

Unfortunately, it looks like the "Database" checkbox is not working and the "Many Files" checkbox is pointing to both "Many Files" and "Database". This means that we don't know when people clicked on the "Database" checkbox and means that we'll have to redo these agency offices. Apologies on our end that we missed this during testing. In any case, this should definitely be resolved before NYC. Thanks.

**Comment by titaniumbones** [comment]
2 grade-school level coding mistakes that I didn't actually test independently, it turns out.  Feel free to test #46, would rather not merge on my own :shamefaced:

**Comment by atesgoral** [comment]
I believe this can be closed as fixed?

**Comment by titaniumbones** [comment]
Yes!

On February 3, 2017 8:57:12 PM EST, Ates Goral <notifications@github.com> wrote:
>I believe this can be closed as fixed?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/edgi-govdata-archiving/eot-nomination-tool/issues/44#issuecomment-277409362

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
