### ISSUE TITLE
Chrome Window Disappears When Switching Browser Windows

### ISSUE THREAD

**Issue by trinberg** [edgi-govdata-archiving/eot-nomination-tool#45]
A few people complained about this, so I wanted to see if this is fixable. Perhaps the window could disappear only when clicking on the screen outside of the extension UI.

**Comment by titaniumbones** [comment]
I htink that's a design choice in the chrome extension framework, so overcoming it would either be impossible or very difficult.  This on the basis of really noghint, though this guy says so so I suppose it could be true: http://stackoverflow.com/questions/14161015/chrome-extension-persistent-popup-best-practices
