### ISSUE TITLE
don't pack docs dir/images in final extension?

### ISSUE THREAD

**Issue by titaniumbones** [edgi-govdata-archiving/eot-nomination-tool#47]
Can I exclude the docs dir from the packed extension? It's over 90% of the total size.

just checking before i exclude

**Comment by atesgoral** [comment]
Yes, ideally we should only ship the files that are actively being used by the extension!

**Comment by dcwalk** [comment]
@titaniumbones can I mark this as complete?

**Comment by titaniumbones** [comment]
done.
