### ISSUE TITLE
Add to chrome store?

### ISSUE THREAD

**Issue by titaniumbones** [edgi-govdata-archiving/eot-nomination-tool#5]
Anyone know how easy it is to add en extension to hte chrome store? If it can be done quickly then maybe we could get this up by tomorrow morning?

**Comment by titaniumbones** [comment]
Created a new account civictechextensions. Can hand creds over to any other CTTO devs. THank you @mi-lee @sonalranjit !

**Comment by mi-lee** [comment]
Wonderful! Thanks @titaniumbones !

**Comment by mi-lee** [comment]
@titaniumbones could you send me the creds as well? I could add some screenshots to make it useful.

**Comment by titaniumbones** [comment]
@mi-lee, 
you should now have admin access to the repo & full write privs to all the other ones in the org account, I think.


Michelle Lee writes:

> @titaniumbones could you send me the creds as well? I could add some screenshots to make it useful.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.


--

**Comment by mi-lee** [comment]
Oh, I meant the Chrome extension store - is it with an associated civic tech gmail account?

**Comment by titaniumbones** [comment]
oh duh, of course.  do I have yr email? 

Michelle Lee writes:

> Oh, I meant the Chrome extension store - is it with an associated civic tech gmail account?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.


--

**Comment by mi-lee** [comment]
michelle.mh.lee92@gmail.com.

Thanks so much! :)

**Comment by sonalranjit** [comment]
Please add me as well sonal.ranjit3@gmail.com

**Comment by titaniumbones** [comment]
published! go team!
