### ISSUE TITLE
Popup closes when a value presented by Chrome's autocomplete is picked by clicking

### ISSUE THREAD

**Issue by atesgoral** [edgi-govdata-archiving/eot-nomination-tool#50]
https://bugs.chromium.org/p/chromium/issues/detail?id=587481

It seems there doesn't seem to be much we can do about this Chrome bug. Tracking here in case anyone else runs into this issue.

Picking the value via keyboard (i.e. arrow down, enter) is fine.

**Comment by dcwalk** [comment]
Marking this wont fix for now! Remove if inappropriate
