### ISSUE TITLE
Custom design

### ISSUE THREAD

**Issue by atesgoral** [edgi-govdata-archiving/eot-nomination-tool#53]
Bootstrap is sooo 2000's.

Working on a tighter layout with a flatter design here: http://codepen.io/atesgoral/pen/GrdLea

(Best viewed on Chrome, for obvious reasons.)

**Comment by titaniumbones** [comment]
Love it. 

On February 4, 2017 3:06:12 AM EST, Ates Goral <notifications@github.com> wrote:
>Bootstrap is sooo 2000's.
>
>Working on a tighter layout with a flatter design here:
>http://codepen.io/atesgoral/pen/GrdLea
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/edgi-govdata-archiving/eot-nomination-tool/issues/53

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by atesgoral** [comment]
Here's the current look:

<img width="593" alt="screen shot 2017-02-04 at 11 33 58 am" src="https://cloud.githubusercontent.com/assets/50832/22619939/ef6a564a-eacd-11e6-9a14-b479437a5cc0.png">

**Comment by atesgoral** [comment]
A few points/questions:

0. Is there a logo I can use in the header?
1. Since we now have more vertical real estate, we can split up the Agency Office fields into different rows and give them full-fledged labels.
2. What's "sub-primer num"? Should it be sub-primer or subprimer?
3. The font looks a bit too chunky on my desktop. I'll test it out on more devices and perhaps make it a bit smaller.

**Comment by atesgoral** [comment]
Still need to add the checkboxes. Latest situation:

<img width="593" alt="screen shot 2017-02-04 at 4 20 30 pm" src="https://cloud.githubusercontent.com/assets/50832/22621663/dc2ad266-eaf6-11e6-9b90-61067e071bd5.png">
<img width="595" alt="screen shot 2017-02-04 at 4 21 46 pm" src="https://cloud.githubusercontent.com/assets/50832/22621664/dc34ebe8-eaf6-11e6-8de0-05f1cd7221cb.png">
<img width="592" alt="screen shot 2017-02-04 at 4 23 24 pm" src="https://cloud.githubusercontent.com/assets/50832/22621665/dc3980f4-eaf6-11e6-9d8a-bc3fb91c0533.png">
<img width="594" alt="screen shot 2017-02-04 at 4 26 41 pm" src="https://cloud.githubusercontent.com/assets/50832/22621666/dc3e10e2-eaf6-11e6-8f45-728a8810d1bc.png">

**Comment by atesgoral** [comment]
Custom checkboxes, more typography tweaks. It's a wrap for now. Will move on to applying this design to the tool and cutting a PR.

<img width="594" alt="screen shot 2017-02-04 at 11 17 44 pm" src="https://cloud.githubusercontent.com/assets/50832/22623654/40e32404-eb30-11e6-9b20-385c47fdfe14.png">

**Comment by mhucka** [comment]
Beautiful work!

**Comment by atesgoral** [comment]
PR #55
