### ISSUE TITLE
update READMe with more elaborate workflow description.  

### ISSUE THREAD

**Issue by titaniumbones** [edgi-govdata-archiving/eot-nomination-tool#57]
I would like to remove the `seedersnsorters` page from the workflow repo, and just point seeders to this repo; we need to eliminate duplication in our docs, and since we will always need a README here, I think it should be here. 

I'm gonna assign to MAT in the hopes b/c they actually know the most about the primer system,etc.  Kick it back to me if you're too busy!

@dcwalk if you don't like htis idea let me know .

**Comment by trinberg** [comment]
Yep - I can follow up on this, but may need to be in a day or two. Will also change the new extension screenshot so it matches the latest version.

**Comment by titaniumbones** [comment]
that's fine, do you think you could have it late wed or early thurs?
would be awesome.

trinberg <notifications@github.com> writes:

> Yep - I can follow up on this, but may need to be in a day or two.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.


--

**Comment by dcwalk** [comment]
I did a wee update in #65 but I don't think this is as expansive as you were thinking?

In my mind there might be more benefit to moving more toward the screencast model (per @danielballan's excellent screencast for the pipeline app) rather than having fuller documentation here). Really not sure though

**Comment by dcwalk** [comment]
I'm going to mark this as closed for now, as it has been updated with the new workflow. Feel free to reopen if further extension is wanted.
