### ISSUE TITLE
multi-input form instead of 'prompt'

### ISSUE THREAD

**Issue by titaniumbones** [edgi-govdata-archiving/eot-nomination-tool#6]
How hard would it be to replace the "prompt" with a simple multi-input form in a small overlay window? If acheivable, this might allow us to capture more data efficiently.

**Comment by titaniumbones** [comment]
Here's someone else's tutorial on how to do this:
https://markb.co.uk/building-a-simple-google-chrome-extension.html
If anyone has time...

**Comment by sonalranjit** [comment]
This is resolved with the new updates from Michelle #8
