### ISSUE TITLE
Need system requirements and possibly other help for chrome extension

### ISSUE THREAD

**Issue by dorasmith** [edgi-govdata-archiving/eot-nomination-tool#62]
What are the system requirements for the Chrome extension?   Eg, what is the minimum version of Chrome that it works with, does it work on phones and tablets, eg, Android, does it need Java and if so what is the minimum version of Java it will run with, does it need javascript installed and enabled, anything else?

You need to have the specific system requirements on the web page that people download the extension from.   

Please keep in mind that even if the extension was created and tested in the latest version of Chrome, that may not be the earliest version it works in, and it is conceivably possible that a version of Chrome can be found for 32 bit Linux that it does run on.

 It is also very possible that the version of Chrome has nothing to do with it, I need some java or javascript feature I've never needed before on my lightweight version of Linux.  It doesn't have every bell and whistle installed like my newer Ubuntu desktop does.   

Please keep in mind that even people running newer 64 bit computers are likely to run 32 bit Linux operating systems if they ever need to run Windows software on it; most people who run Linux and own Windows software have 32 bit software.   Your Chrome extension needs to be able to work in 32 bit Linux.  Also, you are appealing for help to a population of resourceful people who are likely to have gotten online however we can, and that often means older computers and Linux.   

I ask because on my older 32 bit light-weight Xubuntu laptop the extension does not work at all.  It pretends to submit links but Maya established that it didn't.   Nothing autopopulates.   The red statement that this link has been researched before is there when you open it, and never goes away.   

Chrome is installed on my laptop but since the 32 bit linux version has been discontinued it cannot be updated past a certain point.

We tried to install the extension in Chrome on my Android tablet.   It told me it was installing on the desktop, and then could not be found on my desktop.   So if it should work in Chrome I need to know specifically how to install it.  Since the shortcut bar does not install in Linux 

As a suggestion, you might want to make an extension for Firefox.   Firefox uses extensions and is kept up to date in Linux.   

Thanks!

**Comment by dcwalk** [comment]
Hey @dorasmith, thanks for the note! 

In order to help us test, can you provide some more details on your system-- 
(e.g., what version of Chrome)

Also to ensure we understand, did this:
> The red statement that this link has been researched before is there when you open it
...happen across a variety of pages you tested?

I don't believe disabling javascript in chrome would interfere (as it doesn't when I test it), but I'll leave to others to provide more accurate information

**Comment by dorasmith** [comment]
Before we get into that, don't the people who created the extension know what the system requirements are?

**Comment by dorasmith** [comment]
Can you please check and see if the website tiggernut.com, submitted by Dora Smith of DataRescue Austin at about 10:10 AM cst, was really submitted?   I used a primer belonging to a branch of the NOAA web site, and put in the notes that this is a test.    Every single other web site I tried got the this site was already submitted message, but my own little personal web site did not get that message.   

Also, can you please check if the web site, pbs.org, has really been submitted?   Because it told me it has, though it has no more to do with the federal government than my web site does, and I want to make sure it isn't reporting web pages as submitted that aren't.   

I think I've got a workaround that has the tool working.   If it really works, I will post the solution.   It does appear to work at my end, but I need to make sure the pages really submit.   

Also, I've just got the set of files that go with the tool open.   The main page, manifest.json, makes three calls to three javascript scripts, which do all of the tool's functionality, and it also uses flash player.   How could you not know this?   You are someone who is actually qualified to answer the question, what are the system specifications for this Chrome extension, right?  That is the question I asked.   

 Also, javascript cannot be turned on or off in Google Chrome, so it doesn't seem like you could have disabled it in order to see if it works without it.   

Javascript turns out to pack with the browser, and can only be enabled or disabled in that browser, which means among other things that my Linux computers aren't missing it.   

I am having the same problem on my full Ubuntu 14.04 desktop, 32 bit, which has two or three versions of java installed, flash, and all of that.   

Without having yet looked into it, an obvious reason why the tool works in the most recent versoin of Chrome but not last July's version, could be that you are calling APIs that have been introduced into Chrome since last summer.  If so the solution would be to find out which APIs you are using that have been introduced since last summer and use older APIs instead.

**Comment by dorasmith** [comment]
Actually, it looks like you can disable javascript in chrome, even though web discussions say you can't, but I had the box checked to allow all sites to run JavaScript, so that isn't the problem.   On my windows 7 computer I only had an intermediate level checked.

**Comment by dcwalk** [comment]
Hi @dorasmith I didn't develop the app-- I help coordinate across the range of projects we are working on. I asked for more info on your system to help those coming to the issue have a full picture right away.

My comment RE: javascript is based on this setting in chrome's (56.0) preferences:
![screen shot 2017-02-12 at 2 42 44 pm](https://cloud.githubusercontent.com/assets/4692834/22865406/ae683328-f131-11e6-96a1-ed5a5c0fc407.png)
-- good to exclude that as the possible issue, which it sounds like you have.

When you see the message "This URL has already been archived in the last XX days" we are checking against the Internet Archive API, it is not circumscribed to only those federal agency sites we are trying to preserve. Hence why something like PBS would show up, if it is crawlable by IA and has been recently crawled it should be captured by that check.

I can confirm that I am seeing entries with "tiggernut.com," if you could post details about your workaround that would be helpful to the next person.

**Comment by dorasmith** [comment]
I have an idea this thread has turned into a dead horse.   It turns out there is a specific javascript syntax error.   I will close this issue and create a new one.
