### ISSUE TITLE
Update screenshot in the Chrome Store

### ISSUE THREAD

**Issue by dcwalk** [edgi-govdata-archiving/eot-nomination-tool#63]
I want the store to see how fancy the new layout is :)

**Comment by dcwalk** [comment]
~~And here is a screenshot that could be used?~~

**Comment by atesgoral** [comment]
Nitpick: Use [example.com (RFC 2606)](https://tools.ietf.org/html/rfc2606#page-2) for domain examples to prevent accidentally crediting [actual companies](http://www.domain.com/).

**Comment by dcwalk** [comment]
For sure, fixed!

![screen shot 2017-02-13 at 10 05 17 am](https://cloud.githubusercontent.com/assets/4692834/22888537/1a409b06-f1d4-11e6-9469-d0205a9690db.png)

**Comment by dcwalk** [comment]
(tho please clean up my bad crop 😓 )

**Comment by dcwalk** [comment]
Hey @titaniumbones I think you have access to the acct? 
Maybe we trim some of the text too, it looks like the description was from an earlier iteration
