### ISSUE TITLE
ES6 not supported in older browsers

### ISSUE THREAD

**Issue by mi-lee** [edgi-govdata-archiving/eot-nomination-tool#66]
See https://github.com/edgi-govdata-archiving/eot-nomination-tool/blob/master/popup.js#L3

I'm getting emails from a user with an older version of chrome. 

![chromejavascripterror3](https://cloud.githubusercontent.com/assets/8763950/22955842/7c8e4312-f2ec-11e6-8f82-dab52308d2b3.png)
![selection_008](https://cloud.githubusercontent.com/assets/8763950/22955846/7e78a5aa-f2ec-11e6-981d-763f51a7e8ff.png)

**Comment by atesgoral** [comment]
Maybe just adding a `'use strict';` at the top of the file could resolve the above issue.

Beyond ES6, I'm now worried about my use of CSS flexbox...

**Comment by mi-lee** [comment]
Errr.... yeah, we shouldn't be using flexbox. Accessibility >>> convenience for a tool like this

**Comment by mi-lee** [comment]
`use strict` would solve that particular user's issue but given the tiny scope of this project and need for accessibility I'm opting to just go for the added minor inconvenience of switching to ES5

**Comment by atesgoral** [comment]
Fixed by #67
