### ISSUE TITLE
Add fallback for CSS transforms

### ISSUE THREAD

**Issue by atesgoral** [edgi-govdata-archiving/eot-nomination-tool#71]
Older versions of Chrome that don't support CSS transforms should still render the status indicator icons decently.

**Comment by titaniumbones** [comment]
are we still thinking about this?

**Comment by atesgoral** [comment]
It's not a huge issue (only visual) if the cute spinner animations don't work. This shouldn't affect the main functionality of the extension. I'd say it's not worth the effort (which may not be trivial).

**Comment by titaniumbones** [comment]
let's just close it down then...
