### ISSUE TITLE
Transform this into a cool amazing new tool for collaborative data description and ranking

### ISSUE THREAD

**Issue by titaniumbones** [edgi-govdata-archiving/eot-nomination-tool#79]
With the transition to archivers 2.0 and, eventually, mostly machine-based downloading of data, the really interesting role for users is not just to nominate, but to describe and rate datasets.  

This extension could become a really cool piece of that project. Using the Archivers 2.0 auth service, an activist, scientist, or concerned citizen would identify themselves definitively inside the nomination tool.  While using a government dataset, they would click the extension button in the browser and fill out a description of the resource. Archivers 2.0 would feed that ranking back into our collaborative description/ranking tools.  The extension thus becomes a piece of infrastructure for the exciting new world of data-together.  

Tagging @b5, @atesgoral , @mi-lee , @sonalranjit , @dcwalk . 

Hoping you guys can improve the description here while I'm gone!

**Comment by dcwalk** [comment]
Hey! I really dig this idea, but I'm wondering if it would make sense to preserve this as a separate codebase, and imagine this new tool as borrowing heavily from the code and living elsewhere...? It seems like this doesn't have to be "nominating" exactly either, and so maybe we could break out of that idiom with a bit o' space.

**Comment by mi-lee** [comment]
+1 with a separate codebase -- given the level of qualitative information the person has to input perhaps it should be a separate website altogether?

**Comment by dcwalk** [comment]
I'm going to close this, as I think by default we've gone the preservation route :)
